"""merge shared expense into expense, tax restructure

Revision ID: 0f3538379ecd
Revises: f7dbb9231684
Create Date: 2026-04-09 21:36:35.110148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3538379ecd'
down_revision: Union[str, Sequence[str], None] = 'f7dbb9231684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_expenses')
    op.add_column('expenses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('is_shared', sa.Boolean(), nullable=False))
    op.add_column('incomes', sa.Column('description', sa.String(), nullable=True))
    op.add_column('shared_expense_users', sa.Column('expense_id', sa.Integer(), nullable=False))
    op.add_column('shared_expense_users', sa.Column('is_creator', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('shared_expense_users_shared_expense_id_fkey'), 'shared_expense_users', type_='foreignkey')
    op.create_foreign_key(None, 'shared_expense_users', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shared_expense_users', 'shared_expense_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_expense_users', sa.Column('shared_expense_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shared_expense_users', type_='foreignkey')
    op.create_foreign_key(op.f('shared_expense_users_shared_expense_id_fkey'), 'shared_expense_users', 'shared_expenses', ['shared_expense_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shared_expense_users', 'is_creator')
    op.drop_column('shared_expense_users', 'expense_id')
    op.drop_column('incomes', 'description')
    op.drop_column('expenses', 'is_shared')
    op.drop_column('expenses', 'description')
    op.create_table('shared_expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expense_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('shared_expenses_expense_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('shared_expenses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shared_expenses_pkey'))
    )
    # ### end Alembic commands ###
